[[redirects]]
  from = "/library/*"
  to = "http://homeserver.mariosilvaprada.com/library/:splat"
  query = {path = ":path"}
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200