[[redirects]]
  from = "/library/*"
  to = "http://homeserver.mariosilvaprada.com/library/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/books/*"
  to = "http://homeserver.mariosilvaprada.com/library/books/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200